import type {AirportDetails} from './airports';
import type {ReservationData} from './contracts';
type Draft=Omit<ReservationData,'sourceKey'|'sources'>;
// A response may only update its own stage and fields still empty or generated by this lookup.
export function fillAirport<T extends Draft>(draft:T,isEnd:boolean,code:string,airport:AirportDetails|null,previous:AirportDetails|null):T{
 const iata=isEnd?'destinationIata':'originIata',name=isEnd?'destinationAirport':'originAirport',address=isEnd?'destination':'location',point=isEnd?'destinationPoint':'locationPoint';
 if(draft.kind!=='flight'||(draft.flight?.[iata]??'')!==code)return draft;
 const canName=!draft.flight?.[name]?.trim()||!!previous&&draft.flight[name]===previous.name;
 const canAddress=!draft[point]&&(!draft[address]?.trim()||!!previous&&draft[address]===previous.location);
 return {...draft,flight:{...draft.flight,...(canName?{[name]:airport?.name}: {})},...(canAddress?{[address]:airport?.location??''}: {})};
}
