'use client';
import {useId,useRef,useState} from 'react';
import {Check,LoaderCircle,MapPin,Search,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import type {Destination} from '@/lib/geography';
const kindLabel:Record<string,string>={city:'Cidade',town:'Cidade',village:'Localidade',hamlet:'Localidade',municipality:'Município',county:'Município / região',state:'Estado',province:'Província',country:'País',region:'Região',continent:'Continente',district:'Distrito',locality:'Localidade',administrative:'Área administrativa'};
export default function DestinationPicker({value,onChange,legacy='',onLegacyChange}:{value:Destination[];onChange:(v:Destination[])=>void;legacy?:string;onLegacyChange?:(value:string)=>void}){
 const input=useRef<HTMLInputElement>(null);
 const id=useId(),[query,setQuery]=useState(''),[results,setResults]=useState<Destination[]>([]),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[error,setError]=useState(''),epoch=useRef(0);
 async function search(){if(query.trim().length<2||busy)return;const version=++epoch.current;setBusy(true);setError('');setDone(false);try{const response=await fetch('/api/destinations/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query})});const data=await response.json() as {error?:string;results:Destination[]};if(version!==epoch.current)return;if(!response.ok)throw Error(data.error||'Não foi possível buscar destinos.');setResults(data.results);setDone(true);}catch(e){if(version===epoch.current)setError((e as Error).message);}finally{if(version===epoch.current)setBusy(false);}}
 return <div className="destination-picker"><div className="destination-intro"><label htmlFor={id}>Destinos</label><p className="place-help" id={id+'-hint'}>Busque uma cidade, município, estado, região ou país e selecione a correspondência.</p></div>
  {legacy&&<div className="destination-legacy"><span><strong>{legacy}</strong><small>Destino anterior, ainda sem localização confirmada</small></span>{onLegacyChange&&<button type="button" aria-label="Remover destinos anteriores" onClick={()=>onLegacyChange('')}><X/></button>}</div>}
  {value.length>0&&<ul className="destination-selections">{value.map(d=><li key={d.osmType+d.osmId}><MapPin/><span><strong>{d.name}</strong><small>{d.address||kindLabel[d.kind]||'Destino'} · OSM</small></span><button type="button" aria-label={'Remover destino '+d.name} onClick={()=>onChange(value.filter(v=>v.osmType!==d.osmType||v.osmId!==d.osmId))}><X/></button></li>)}</ul>}
  {value.length<20&&<><div className="place-lookup-row"><input ref={input} id={id} aria-describedby={id+'-hint'} value={query} maxLength={200} placeholder="Ex.: Lisboa, Portugal" onChange={e=>{setQuery(e.target.value);setResults([]);setDone(false);setError('');epoch.current++;setBusy(false);}} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();void search();}}}/><Button type="button" variant="outline" disabled={busy||query.trim().length<2} onClick={()=>void search()}>{busy?<LoaderCircle className="spin"/>:<Search/>}Buscar</Button></div>
  {results.length>0&&<div className="search-results destination-results" aria-label="Destinos encontrados">{results.map(d=>{const selected=value.some(v=>v.osmId===d.osmId&&v.osmType===d.osmType);return <button type="button" disabled={selected} key={d.osmType+d.osmId} onClick={()=>{onChange([...value,d]);setQuery('');setResults([]);setDone(false);input.current?.focus();}}><strong>{d.name}{selected&&<Check/>}</strong><small>{kindLabel[d.kind]||'Região'}{d.address?' · '+d.address:''}</small></button>;})}</div>}
  {done&&!results.length&&<p role="status" className="place-help">Nenhum destino encontrado. Inclua o estado ou o país na busca.</p>}{error&&<p role="alert" className="form-error">{error}</p>}</>}
  <p className="place-help destination-attribution">Dados do <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">OpenStreetMap</a>, via Photon. Você pode adicionar destinos depois.</p>
 </div>;
}
